lib/instagram_web/router.ex
defmodule InstagramWeb.Router do
  use InstagramWeb, :router

  pipeline :browser do
    plug :accepts, ["html"]
    plug :fetch_session
    plug :fetch_live_flash
    plug :put_root_layout, {InstagramWeb.LayoutView, :root}
    plug :protect_from_forgery
    plug :put_secure_browser_headers
  end

  pipeline :api do
    plug :accepts, ["json"]
  end

  scope "/", InstagramWeb do
    pipe_through :browser

    get "/", PageController, :index
    resources "/feeds", FeedController do
      post "/message", FeedController, :add_message

    end
    post "/search", FeedController ,:search


  end

  # Other scopes may use custom stacks.
  # scope "/api", InstagramWeb do
  #   pipe_through :api
  # end

  # Enables LiveDashboard only for development
  #
  # If you want to use the LiveDashboard in production, you should put
  # it behind authentication and allow only admins to access it.
  # If your application does not have an admins-only section yet,
  # you can use Plug.BasicAuth to set up some basic authentication
  # as long as you are also using SSL (which you should anyway).
  if Mix.env() in [:dev, :test] do
    import Phoenix.LiveDashboard.Router

    scope "/" do
      pipe_through :browser
      live_dashboard "/dashboard", metrics: InstagramWeb.Telemetry
    end
  end

  # Enables the Swoosh mailbox preview in development.
  #
  # Note that preview only shows emails that were sent by the same
  # node running the Phoenix server.
  if Mix.env() == :dev do
    scope "/dev" do
      pipe_through :browser

      forward "/mailbox", Plug.Swoosh.MailboxPreview
    end
  end
end

lib/instagram/feeds.ex
defmodule Instagram.Feeds do
  @moduledoc """
  The Feeds context.
  """

  import Ecto.Query, warn: false
  alias Instagram.Repo

  alias Instagram.Feeds.Feed
  alias Instagram.Messages

  @doc """
  Returns the list of feeds.

  ## Examples

      iex> list_feeds()
      [%Feed{}, ...]

  """
  def list_feeds do
    Repo.all(Feed)
  end

  @doc """
  Gets a single feed.

  Raises `Ecto.NoResultsError` if the Feed does not exist.

  ## Examples

      iex> get_feed!(123)
      %Feed{}

      iex> get_feed!(456)
      ** (Ecto.NoResultsError)

  """
  def get_feed!(id), do: Repo.get!(Feed, id)

  @doc """
  Creates a feed.

  ## Examples

      iex> create_feed(%{field: value})
      {:ok, %Feed{}}

      iex> create_feed(%{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def create_feed(attrs \\ %{}) do
    %Feed{}
    |> Feed.changeset(attrs)
    |> Repo.insert()
  end

  @doc """
  Updates a feed.

  ## Examples

      iex> update_feed(feed, %{field: new_value})
      {:ok, %Feed{}}

      iex> update_feed(feed, %{field: bad_value})
      {:error, %Ecto.Changeset{}}

  """
  def update_feed(%Feed{} = feed, attrs) do
    feed
    |> Feed.changeset(attrs)
    |> Repo.update()
  end

  @doc """
  Deletes a feed.

  ## Examples

      iex> delete_feed(feed)
      {:ok, %Feed{}}

      iex> delete_feed(feed)
      {:error, %Ecto.Changeset{}}

  """
  def delete_feed(%Feed{} = feed) do
    Repo.delete(feed)
  end

  @doc """
  Returns an `%Ecto.Changeset{}` for tracking feed changes.

  ## Examples

      iex> change_feed(feed)
      %Ecto.Changeset{data: %Feed{}}

  """
  def change_feed(%Feed{} = feed, attrs \\ %{}) do
    Feed.changeset(feed, attrs)
  end

  def add_message(feed_id, message_params) do
    message_params
    |> Map.put("feed_id", feed_id)
    |> Messages.create_message()
  end
  def search(search_params) do
    query = from(f in Feed, where: fragment("? ILIKE ?", f.author, ^"%#{search_params}%") or fragment("? ILIKE ?", f.title, ^"%#{search_params}%"))
    feeds = Repo.all(query)

  end


end

lib/instagram/feeds/feed.ex
defmodule Instagram.Feeds.Feed do
  use Ecto.Schema
  import Ecto.Changeset
  alias Instagram.Messages.Message

  schema "feeds" do
    field :body, :string
    field :title, :string
    has_many :messages, Message


    timestamps()
  end

  @doc false
  def changeset(feed, attrs) do
    feed
    |> cast(attrs, [:title, :body])
    |> validate_required([:title, :body])
  end
end

lib/instagram_web/controllers/feed_controller.ex
defmodule InstagramWeb.FeedController do
  use InstagramWeb, :controller

  alias Instagram.Feeds
  alias Instagram.Feeds.Feed
  alias Instagram.Messages.Message
  alias Instagram.Repo
  import Ecto.Query, warn: false


  def index(conn, params) do
    IO.inspect(conn.params)
    IO.write("conn params above")
    query = from(f in Feed,  where: f.title == "this is a new feed",select: f)
    page = query
              |>Repo.paginate(params )
    changeset = Feeds.change_feed(%Feed{})
    IO.inspect(changeset)

    render(conn, "index.html", feeds: page.entries, changeset: changeset, page: page)
  end

  def new(conn, _params) do
    changeset = Feeds.change_feed(%Feed{})
    render(conn, "new.html", changeset: changeset)
  end

  def create(conn, %{"feed" => feed_params}) do
    case Feeds.create_feed(feed_params) do
      {:ok, feed} ->
        conn
        |> put_flash(:info, "Feed created successfully.")
        |> redirect(to: Routes.feed_path(conn, :show, feed))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "new.html", changeset: changeset)
    end
  end

  def show(conn, %{"id" => id}) do
    feed = Feeds.get_feed!(id)
    changeset = Message.changeset(%Message{},%{})
    render(conn, "show.html", feed: feed, changeset: changeset )
  end

  def edit(conn, %{"id" => id}) do
    feed = Feeds.get_feed!(id)
    changeset = Feeds.change_feed(feed)
    render(conn, "edit.html", feed: feed, changeset: changeset)
  end

  def update(conn, %{"id" => id, "feed" => feed_params}) do
    feed = Feeds.get_feed!(id)

    case Feeds.update_feed(feed, feed_params) do
      {:ok, feed} ->
        conn
        |> put_flash(:info, "Feed updated successfully.")
        |> redirect(to: Routes.feed_path(conn, :show, feed))

      {:error, %Ecto.Changeset{} = changeset} ->
        render(conn, "edit.html", feed: feed, changeset: changeset)
    end
  end

  def delete(conn, %{"id" => id}) do
    feed = Feeds.get_feed!(id)
    {:ok, _feed} = Feeds.delete_feed(feed)

    conn
    |> put_flash(:info, "Feed deleted successfully.")
    |> redirect(to: Routes.feed_path(conn, :index))
  end

  def add_message(conn, %{"message" => message_params, "feed_id" => feed_id}) do
    feed =
      feed_id
      |> Feeds.get_feed!()
      |> Repo.preload(:messages)
    case Feeds.add_message(feed_id, message_params) do
      {:ok, _message} ->
        conn
        |> put_flash(:info, "message added :)")
        |> redirect(to: Routes.feed_path(conn, :show, feed))
      {:error, _error} ->
        conn
        |> put_flash(:error, "message not added :(")
        |> redirect(to: Routes.feed_path(conn, :show, feed))
    end

  end





# def search(conn,"feed" => %{"search" => search_params}) do
#   IO.write("conn_params")
#   IO.inspect(conn.params)
#   feeds = Feeds.search(search_params)
#  changeset = Feeds.change_feed(%Feed{})

#  conn
#  |> put_flash(:danger, "Feed search not successfully.")
#  |> render( "index.html", feeds: [], changeset: changeset)

#  end

 end


#  def search(conn, %{"feed" => %{"search" => search_params}}) do
#   feeds = Feedback.search_me(search_params)
#   search_changeset= Feedback.change_feed(%Feed{})
#   case feeds do
#   [] ->
#   conn
#   |> put_flash(:danger, "Feed search not successfully.")
#   |> render( "index.html", feeds: [], search_changeset: search_changeset)
#   _ ->
#   conn

#   |> put_flash(:info, "Feed search successfully.")

#   |> render( "index.html", feeds: feeds, search_changeset: search_changeset)

#   end

#   end

lib/instagram_web/views/feed_view.ex
defmodule InstagramWeb.FeedView do
  use InstagramWeb, :view
  import Scrivener.HTML
end

lib/instagram_web/templates/feed/edit.html.heex
<h1>Edit Feed</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.feed_path(@conn, :update, @feed)) %>

<span><%= link "Back", to: Routes.feed_path(@conn, :index) %></span>

lib/instagram_web/templates/feed/form.html.heex
<.form let={f} for={@changeset} action={@action}>
  <%= if @changeset.action do %>
    <div class="alert alert-danger">
      <p>Oops, something went wrong! Please check the errors below.</p>
    </div>
  <% end %>

  <%= label f, :title %>
  <%= text_input f, :title %>
  <%= error_tag f, :title %>

  <%= label f, :body %>
  <%= textarea f, :body %>
  <%= error_tag f, :body %>

  <div>
    <%= submit "Save" %>
  </div>
</.form>

lib/instagram_web/templates/feed/index.html.heex
<h1>Listing Feeds</h1>
  
  <%= pagination_links @page, view_style: :foundation %>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>

      <th></th>
    </tr>
  </thead>
  <tbody>
<%= for feed <- @feeds do %>
    <tr>
      <td><%= feed.title %></td>
      <td><%= feed.body %></td>

      <td>
        <span><%= link "Show", to: Routes.feed_path(@conn, :show, feed) %></span>
        <span><%= link "Edit", to: Routes.feed_path(@conn, :edit, feed) %></span>
        <span><%= link "Delete", to: Routes.feed_path(@conn, :delete, feed), method: :delete, data: [confirm: "Are you sure?"] %></span>
      </td>
    </tr>
<% end %>
  </tbody>
</table>

<span><%= link "New Feed", to: Routes.feed_path(@conn, :new) %></span>

lib/instagram_web/templates/feed/message.html.heex
<%= form_for @changeset, @action, fn f -> %>
  <div class="form-group">
   <label>Name</label>
   <%= text_input f, :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <label>Content</label>
    <%= textarea f, :content, class: "form-control" %>
  </div>
  
  <div class="form-group">
    <%= submit "Add comment", class: "btn btn-primary" %>
  </div>
<% end %>

lib/instagram_web/templates/feed/new.html.heex
<h1>New Feed</h1>

<%= render "form.html", Map.put(assigns, :action, Routes.feed_path(@conn, :create)) %>

<span><%= link "Back", to: Routes.feed_path(@conn, :index) %></span>

lib/instagram_web/templates/feed/new_search.html.heex
   <%= render "search.html", Map.put(assigns, :action, Routes.feed_path(@conn, :search)) %>

lib/instagram_web/templates/feed/search.html.heex
<.form let={f} for={@changeset} action={@action}>

 <%= if @changeset.action do %>

 <div class="alert alert-danger">
 <p>Oops, something went wrong! Please check the errors below.</p>
 </div>
 <% end %>
 <%= label f, :search %>
 <%= text_input f, :search, style: "border: 2px solid black;" %>
 <%= error_tag f, :search %>
 <div>
 <%= submit "search" %>
 </div>
</.form>

lib/instagram_web/templates/feed/show.html.heex
<h1>Show Feed</h1>

<ul>

  <li>
    <strong>Title:</strong>
    <%= @feed.title %>
  </li>

  <li>
    <strong>Body:</strong>
    <%= @feed.body %>
  </li>

</ul>
<%= render "message.html", feed: @feed, changeset: @changeset, action: Routes.feed_feed_path(@conn, :add_message, @feed) %>


<span><%= link "Edit", to: Routes.feed_path(@conn, :edit, @feed) %></span> |
<span><%= link "Back", to: Routes.feed_path(@conn, :index) %></span>